version: '3'
services:
  playground:
    container_name: 'dotnet'
    hostname: 'dotnet'
    build: .
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace
